name: synchro_share
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: 3.35.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # State Management
  bloc: any
  equatable: any

  # Dependency Injection
  get_it: any
  injectable: any

  # Local Storage
  hive: any
  hive_flutter: any
  path_provider: any

  # Navigation
  go_router: any

  # UI
  flutter_screenutil: any
  responsive_framework: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

  # To change package name via command
  change_app_package_name: any

  #
  hive_generator: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/